# Generated by Django 6.0.2 on 2026-02-22 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('streamer_login', models.CharField(blank=True, max_length=255, null=True)),
                ('streamer_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('length_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('commenter_login', models.CharField(blank=True, max_length=255, null=True)),
                ('commenter_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_offset_seconds', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scraper.video')),
            ],
        ),
    ]
