# Generated by Django 6.0.2 on 2026-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_streamer_scrapetask_video_streamer'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
