# Generated by Django 6.0.2 on 2026-02-25 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_toxic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='toxicity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClassificationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=50)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_tasks', to='scraper.video')),
            ],
        ),
    ]
