# Generated by Django 6.0.2 on 2026-02-27 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_comment_is_toxic_comment_toxicity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('streamladder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='scraper.streamer')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='scraper.video')),
            ],
        ),
    ]
