# Generated by Django 6.0.2 on 2026-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='s3_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
