# Generated by Django 6.0.2 on 2026-02-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_clip_s3_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='youtube_video_id',
        ),
    ]
