# Generated by Django 6.0.2 on 2026-03-01 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_remove_clip_youtube_url_remove_clip_youtube_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='scraper.streamer')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='scraper.video')),
            ],
        ),
    ]
